services:
  - type: web
    name: flask-login-demo
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        value: your_secret_key